language: node_js
node_js:
  - "12"
addons:
  code_climate:
    repo_token: 87feacd05a49c0f710303701e7802f2edd591321104d2ad3aeef12005905f316 
before_script:
after_script:
  - codeclimate-test-reporter < lcov.info